### ISSUE TITLE
in WSL2, to instantiate Waifu2x fallbacks to llvmpipe, not NVIDIA Geforce drvier.

### ISSUE THREAD

**Issue by lovelyPuppies** [Final2x/waifu2x-ncnn-py#8]
Environment:
- GPU: NVIDIA 1080 Ti
- GeForce driver: NVIDIA Game Ready Driver 546.33
- Window version: Windows 11 21H2 (22000.2518)
---------------

1. when I use Waifu2x Snowshell GUI tools in Windows,
> [0 NVIDIA GeForce GTX 1080 Ti]  queueC=2[8]  queueG=0[16]  queueT=1[2]
> [0 NVIDIA GeForce GTX 1080 Ti]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
> [0 NVIDIA GeForce GTX 1080 Ti]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
> [0 NVIDIA GeForce GTX 1080 Ti]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

to process image in Windows11, everything is OK.

----------------------

2. when I use this library in WSL2 (Ubuntu22.04)
> [0 llvmpipe (LLVM 15.0.7, 256 bits)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
> [0 llvmpipe (LLVM 15.0.7, 256 bits)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
> [0 llvmpipe (LLVM 15.0.7, 256 bits)]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
> [0 llvmpipe (LLVM 15.0.7, 256 bits)]  subgroup=8  basic=1  vote=1  ballot=1  shuffle=1

to process image in WSL2 causes infinite waiting. (not completes)

**Comment by Tohrusky** [comment]
wsl2 and wsa should not support vulkan by default, so it won't work correctly

https://github.com/Tencent/ncnn/issues/3867

**Comment by Tohrusky** [comment]
其实多等一会也能跑出来的，倒不如直接用cpu
